server:
  servlet:
    context-path: /api/v1/
  port: ${MS_BACKEND_PORT:8080}

spring:
  data:
    mongodb:
      database: ${POSTGRES_DB:ms-db}
      host: ${POSTGRES_HOST:localhost}
      port: ${POSTGRES_PORT:27017}
  jpa:
    hibernate:
      ddl-auto: update
