server:
  servlet:
    context-path: /api/v1/
  port: ${MS_BACKEND_PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:ms-backend}