server:
  port: ${MS_BACKEND_PORT:8080}

spring:
  data:
    mongodb:
      database: ${MONGO_DB:ms-db}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
  jpa:
    hibernate:
      ddl-auto: update